version: '3.5'
services:
  dipex:
    image: amancevice/dipex
    build: .
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      TEST:
    volumes:
      - ~/.aws:/root/.aws:ro
