version: '3.7'
services:
  aws:
    image: awscli
    build: .
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
      AWS_REGION:
      AWS_PROFILE:
    volumes:
      - ~/.aws:/root/.aws:ro
